App/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired()])
    content = TextAreaField('Content',validators=[DataRequired()])
    submit =  SubmitField('Post')

App/main/routes.py
#main_routesss
from flask import Blueprint , render_template,request
from App.models import Post

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home") #home page route
def home():
    page = request.args.get('page',1,type=int)
    posts =  Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    #order by helps to show the latest post first
    return render_template('home.html',posts=posts)

#About Page route
@main.route("/about")
def about():
    return render_template('about.html',title='About')

App/posts/routes.py
#posts_routes.py
from flask import ( render_template,url_for,flash,
                    redirect,request,abort,  Blueprint)
from flask_login import current_user,login_required
from App import db
from App.models import Post
from App.posts.forms import PostForm

posts = Blueprint('posts', __name__)


#new post
@posts.route("/post/new" , methods= ['GET','POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title = form.title.data , content = form.content.data ,author =  current_user)
        db.session.add(post)
        db.session.commit()
        flash("your post has been created" , 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html',title='New Post',form =form ,legend= 'New Post')


# getting to the post via post_id and displaying indiviuallly
@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id) #give me the id or return 404 if id doesnot exixts
    return render_template('post.html' , title = post.title , post=post)

# Updating the post 
@posts.route("/post/<int:post_id>/update",methods= ['GET','POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403) #403 response is for http response for forbidden route 
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit() #directly commiting as it is already in data bases
        flash("your post has been updated ", 'success')
        print("Post updated")
        return redirect(url_for('posts.post',post_id = post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html',title='Update Post',form =form , legend= 'Update Post')
    
#Deelete post route
@posts.route("/post/<int:post_id>/delete",methods= ['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403) #403 response is for http response for forbidden rou
    db.session.delete(post)
    db.session.commit()
    flash('Your post hass been deleted', 'success')
    return redirect(url_for('main.home'))

App/users/routes.py
#users_routes.py
# contains 
# >register 
# >login
# >logout
# >account
# >user_posts
# >reset_request
# >reset_token

from flask import render_template,url_for,flash,redirect,request, Blueprint
from flask_login import login_user,current_user,logout_user,login_required
from App import db,bcrypt
from App.models import User,Post
from App.users.forms import (RegistrationForm , LoginForm , UpdateAccoutForm ,
                                RequestResetForm , ResetPasswordForm)
from App.users.utils import save_picture,send_reset_email

users = Blueprint('users', __name__)
#Blueprint('blueprint_name', __name__ (this is mandatory to specify it's a blueprint name))

#Registration page route
@users.route("/register" , methods= ['GET','POST']) #givng list of allowed methods
def register():
    if current_user.is_authenticated:
        print("you are already logged in ")
        return redirect(url_for('main.home'))
    form = RegistrationForm() #creating an instance of registration form
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username = form.username.data , email = form.email.data , password = hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your accout is created ! you will be able to log in','success')
        #print('Your accout is created ! you will be able to log in')
        return redirect(url_for('users.login'))
    return render_template('register.html', title ='Registration Page' , form = form) 
    # the last field is passing our registrationform on above line

#Log in page route
@users.route("/login", methods= ['GET','POST'])
def login():
    if current_user.is_authenticated:
        print("you are already logged in ")
        return redirect(url_for('main.home'))
    form = LoginForm() #creating an instance of login form
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password , form.password.data):
            login_user(user,remember=form.remember.data)
            next_page = request.args.get('next') # to get the next page from the querey passed before login required
            print("Logged in successfully")
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
            #redirect to nect page if next_page exits else redirect to home
        else:
            print("Unsuccessful log in ")
            flash('Unsuccessful Log in Please check password','error')
    return render_template('login.html', title ='Log In Page' , form = form) 
    # the last field is passing our loginform on above line

#Log out
@users.route("/logout")
def logout():
    logout_user()
    print("You are logged out ")
    return redirect(url_for('main.home'))


#Accoutn 
@users.route("/account", methods= ['GET','POST'])
@login_required   #to keep a check for log in required
def account():
    form = UpdateAccoutForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file

        current_user.username = form.username.data 
        current_user.email = form.email.data
        db.session.commit()
        print("Account updated")
        flash('Your account has been updated','success')
        return redirect(url_for('users.account'))
    elif request.method=='GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static',filename='profile_pics/'+current_user.image_file)
    return render_template('account.html',title='Account',image_file =  image_file, form = form)

#displaying only post by the clicked user
@users.route("/user/<string:username>") 
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user =  User.query.filter_by(username=username).first_or_404() #if found return else 404
    posts =  Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
        #\ is used to break the qurey in diff lines . filter_by(author=user) filter the post only by that user
    #order by helps to show the latest post first
    return render_template('user_posts.html',posts=posts ,user=user)


#reseting our request 
@users.route("/reset_password" , methods= ['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        #now once we have the user we need to send him a email with a token
        send_reset_email(user)
        print("an email has been sent with instruction ")
        flash('An email has been sent with instructions to reset your passsword','info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html',title='Reset Password' , form = form)

#route to set the password by accepting token from user 
@users.route("/reset_password/<token>" , methods= ['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None :
        print("That is an invalid or expired token")
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form =  ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your accout is created ! you will be able to log in','success')
        print('Your password is updated')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html',title ='Reset Password',form = form)

App/templates/about.html
{% extends "layout.html" %}
{% block content %}

    <h1>ABout page  nice its still wokring</h1>
    
{% endblock content %}

App/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <div class="media-left " >
                <img class=" rounded-circle account-img "  src="{{ image_file }}">
                    
            </div>            
            <div class="media-body" >
                
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary"> {{ current_user.email }} </p>
            </div> 
        </div>
        
        <!-- Update form -->
            <form method="POST" action="" enctype="multipart/form-data"> 
                <!-- enctype is must -->
                <!-- action set to empty string implies that it is going to POSt the informationto 
                same route that we are currently on  -->
                {{ form.hidden_tag() }} 
                <!-- hiddentag adds a CSRF(Cross site request forgery token) -->
    
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Account Info</legend>
                    
                    <div class="form-group mb-4">
                        {{ form.username.label(class = "form-control-label") }}
    
                            {% if form.username.errors %}
                                {{ form.username(class = "form-control form-control-lg is-invalid") }}
                                <div class="invalid-feeback">
                                    {% for error in form.username.errors %}
                                        <span> {{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else  %}
                                {{ form.username(class = "form-control form-control-lg") }}
                            {% endif %}
    
                        
                    </div>
    
                    <div class="form-group mb-4">
                        {{ form.email.label(class = "form-control-label") }}
    
                        {% if form.email.errors %}
                                {{ form.email(class = "form-control form-control-lg is-invalid") }}
                                <div class="invalid-feeback">
                                    {% for error in form.email.errors %}
                                        <span> {{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else  %}
                            {{ form.email(class = "form-control form-control-lg") }}
                            {% endif %}     
                    </div>
                    <!-- For profile picture -->
                    <div class="form-group mb-4">
                        {{ form.picture.label() }} <br><br>
                        {{ form.picture (class = "form-control-file" )}}
                        {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <span class="text-danger"> {{ error }}</span>  </br>
                            {% endfor %}
                        {% endif %}
                    </div>
    
                </fieldset>
                
                <div class="form-group mb-4">
                    {{form.submit(class="btn btn-outline-info")}}
                </div>
    
            </form>
        

    </div>
    
{% endblock content %}

App/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action=""> 
        <!-- action set to empty string implies that it is going to POSt the informationto 
        same route that we are currently on  -->
        {{ form.hidden_tag() }} 
        <!-- hiddentag adds a CSRF(Cross site request forgery token) -->

        <fieldset class="form-group">
            <legend class="border-bottom mb-4"> <h2>{{legend}}</h2> </legend>

            <div class="form-group mb-4">
                {{ form.title.label(class = "form-control-label") }}

                {% if form.title.errors %}
                        {{ form.title(class = "form-control form-control-lg is-invalid") }}
                        <div class="invalid-feeback">
                            {% for error in form.title.errors %}
                                <span> {{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else  %}
                    {{ form.title(class = "form-control form-control-lg") }}
                    {% endif %} 

                
            </div>

            <div class="form-group mb-4">
                {{ form.content.label(class = "form-control-label") }}
                {% if form.content.errors %}
                        {{ form.content(class = "form-control form-control-lg is-invalid") }}
                        <div class="invalid-feeback">
                            {% for error in form.content.errors %}
                                <span> {{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else  %}
                        {{ form.content(class = "form-control form-control-lg") }}
                    {% endif %}     
            </div>
            
            


        </fieldset>
        
        <div class="form-group mb-4">
            {{form.submit(class="btn btn-outline-info")}}
        </div>
    </form>
</div>

{% endblock content %}

App/templates/home.html
{% extends "layout.html" %}
{% block content %}

    <!-- To show the articls of home pge -->
    {%for post in posts.items %}
        <article class="media content-section">
            <!-- article img is from main.css -->
            <div class="media-object " > 
                <img class=" media-object rounded-circle article-img " src=" {{ url_for('static',filename = 'profile_pics/' + post.author.image_file)}}">
            </div>
            
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-5 mt-0 " href=" {{url_for('users.user_posts', username=post.author.username )}}"> {{ post.author.username  }}</a>  
                    <!-- .username is added to only give out user name of author and strftime is used to show date time as our requirement-->
                    <small class="text-muted ml-6"> {{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2><a class="article-title" href=" {{url_for('posts.post',post_id=post.id)}}"> {{ post.title }}</a></h2>
                <p class="article-content"> {{ post.content}}</p>
            </div>
        </article>    
        {% endfor %}

    

    <!-- To iterate betweeen multiples pages shown on home screen -->
    {% for page_num in posts.iter_pages(left_edge=1 ,right_edge=1 , left_current=1, right_current=2) %} 
    <!-- left_edge and right_edge tells how many pages on the far  left/right of the links to be displayed -->
    <!-- left_current and right_current tells how many pages on the left/right will show up ,right current inclues  current page-->
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('main.home' , page=page_num )}}"> {{ page_num }}</a>
                {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home' , page=page_num )}}"> {{ page_num }}</a>
                {% endif %}
            {% else %}
                ....
            {% endif %}
    {% endfor %}
    
{% endblock content %}

App/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
       <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

      {% if title %}
          <title>Flask Blog - {{ title }}</title>
      {% else %}
          <title>Flask Blog</title>
      {% endif %}
    </head>
    <body>

        <!-- NAVIGATION BAR -->
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top py-3" style="background-color: rgb(25, 58, 68);">
              <div class="container">
                <a class="navbar-brand mr-4" href="/">Flask Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle" >
                  <div class="navbar-nav mr-auto" >
                    <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                    <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                  </div>
                  <!-- Navbar Right Side -->
                  <div class="navbar-nav "  style="margin-left: auto;">
                    {% if current_user.is_authenticated %}
                      <a class="nav-item nav-link"  href="{{ url_for('posts.new_post') }}">New Post</a>
                      <a class="nav-item nav-link"  href="{{ url_for('users.account') }}">Account</a>
                      <a class="nav-item nav-link"  href="{{ url_for('users.logout') }}">Log out</a>
                    {% else %}
                      <a class="nav-item nav-link"  href="{{ url_for('users.login') }}">Login</a>
                      <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </nav>
          </header>

        <!-- Main Contents -->
        <main role="main" class="container">
            <div class="row">
              <div class="col-md-8">
                {% with messgaes= get_flashed_messages(with_categories=true) %}
                    {%if messages %}
                        {% for category,message in messages  %}
                             <div class="alert alert-{{ category }}">
                                 {{ message }}
                             </div>
                        {% endfor %}

                    {% endif %}
                {% endwith%}

                {% block content %}{% endblock %}
              </div>
              <div class="col-md-4">
                <div class="content-section">
                  <h3>Our Sidebar</h3>
                  <p class='text-muted'>You can put any information here you'd like.
                    <ul class="list-group">
                      <li class="list-group-item list-group-item-light">Latest Posts</li>
                      <li class="list-group-item list-group-item-light">Announcements</li>
                      <li class="list-group-item list-group-item-light">Calendars</li>
                      <li class="list-group-item list-group-item-light">etc</li>
                    </ul>
                  </p>
                </div>
              </div>
            </div>
          </main>
        

       
    </body>
</html>

App/templates/login.html
{% extends "layout.html" %}
{% block content %}

    <div class="content-section">
        <form method="POST" action=""> 
            <!-- action set to empty string implies that it is going to POSt the informationto 
            same route that we are currently on  -->
            {{ form.hidden_tag() }} 
            <!-- hiddentag adds a CSRF(Cross site request forgery token) -->

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">LOG IN</legend>

                <div class="form-group mb-4">
                    {{ form.email.label(class = "form-control-label") }}

                    {% if form.email.errors %}
                            {{ form.email(class = "form-control form-control-lg is-invalid") }}
                            <div class="invalid-feeback">
                                {% for error in form.email.errors %}
                                    <span> {{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else  %}
                        {{ form.email(class = "form-control form-control-lg") }}
                        {% endif %} 

                    
                </div>

                <div class="form-group mb-4">
                    {{ form.password.label(class = "form-control-label") }}
                    {% if form.password.errors %}
                            {{ form.password(class = "form-control form-control-lg is-invalid") }}
                            <div class="invalid-feeback">
                                {% for error in form.password.errors %}
                                    <span> {{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else  %}
                            {{ form.password(class = "form-control form-control-lg") }}
                        {% endif %}     
                </div>
                
                <div class="form-check">
                    {{ form.remember(class="form-check-input" )}}
                    {{ form.remember.label(class="form-check-label" )}}
                </div>


            </fieldset>
            
            <div class="form-group mb-4">
                {{form.submit(class="btn btn-outline-info")}}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}"> Forgotten password ? </a>
                </small>
            </div>
            
        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted"> 
            Need an account ? <a class="ml-2" href="{{ url_for('users.register') }}"> Sign Up now</a>
            <!-- In url_for we pass the name of the function of the route we want to call--> 
        </small>

    </div>
    
{% endblock content %}

App/templates/post.html
{% extends "layout.html" %}
{% block content %}
        <article class="media content-section">
            <!-- article img is from main.css -->
            <div class="media-object " > 
                <img class=" media-object rounded-circle article-img " src=" {{ url_for('static',filename = 'profile_pics/' + post.author.image_file)}}">
            </div>
            
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-5 mt-0 " href=" {{url_for('users.user_posts', username=post.author.username )}}"> {{ post.author.username  }}</a>  
                    <!-- .username is added to only give out user name of author and strftime is used to show date time as our requirement-->
                    <small class="text-muted ml-6"> {{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                    {% if post.author == current_user %}
                        <div>
                            <a  class="btn btn-secondary btn-sm mt-1 mb-1" href=" {{ url_for('posts.update_post',post_id = post.id) }}">Update</a>
                            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal"> 
                                Delete 
                            </button>
                        </div>
                    {% endif %}


                </div>
                <h2 class="article-title" > {{ post.title }}</h2>
                <p class="article-content"> {{ post.content}}</p>
            </div>
        </article>    
    
    <!-- Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post  ?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                        <p>Are you sure you want to delete  : <b>{{ post.title }}</b> ?</p>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <!-- <button type="button" class="btn btn-primary">Save changes</button> -->

                <form action="{{ url_for('posts.delete_post',post_id=post.id) }}" method="POST">  
                    <!-- action to go to the delete post route -->
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
                </div>
            </div>
            </div>
        </div>

       
{% endblock content %}

App/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}

    <div class="content-section">
        <form method="POST" action=""> 
            <!-- action set to empty string implies that it is going to POSt the informationto 
            same route that we are currently on  -->
            {{ form.hidden_tag() }} 
            <!-- hiddentag adds a CSRF(Cross site request forgery token) -->

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>

                <div class="form-group mb-4">
                    {{ form.email.label(class = "form-control-label") }}

                    {% if form.email.errors %}
                            {{ form.email(class = "form-control form-control-lg is-invalid") }}
                            <div class="invalid-feeback">
                                {% for error in form.email.errors %}
                                    <span> {{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else  %}
                        {{ form.email(class = "form-control form-control-lg") }}
                        {% endif %} 
                </div>
            </fieldset>
            <div class="form-group mb-4">
                {{form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>
    
{% endblock content %}

App/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}

    <h1 class="mb-3">
        Post by {{ user.username }} . ({{ posts.total }})

    </h1>

    <!-- To show the articls of home pge -->
    {%for post in posts.items %}
        <article class="media content-section">
            <!-- article img is from main.css -->
            <div class="media-object " > 
                <img class=" media-object rounded-circle article-img " src=" {{ url_for('static',filename = 'profile_pics/' + post.author.image_file)}}">
            </div>
            
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-5 mt-0 " href=" {{url_for('users.user_posts', username=post.author.username )}}"> {{ post.author.username  }}</a> 
                    <!-- .username is added to only give out user name of author and strftime is used to show date time as our requirement-->
                    <small class="text-muted ml-6"> {{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2><a class="article-title" href=" {{url_for('posts.post',post_id=post.id)}}"> {{ post.title }}</a></h2>
                <p class="article-content"> {{ post.content}}</p>
            </div>
        </article>    
        {% endfor %}

    

    <!-- To iterate betweeen multiples pages shown on home screen -->
    {% for page_num in posts.iter_pages(left_edge=1 ,right_edge=1 , left_current=1, right_current=2) %} 
    <!-- left_edge and right_edge tells how many pages on the far  left/right of the links to be displayed -->
    <!-- left_current and right_current tells how many pages on the left/right will show up ,right current inclues  current page-->
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts' , username=user.username ,  page=page_num )}}"> {{ page_num }}</a>
                {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts' , username=user.username , page=page_num )}}"> {{ page_num }}</a>
                {% endif %}
            {% else %}
                ....
            {% endif %}
    {% endfor %}
    
{% endblock content %}